# Generated by Django 3.0.5 on 2021-07-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20210714_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
